# Taken from:
# https://github.com/dockerfile/redis

FROM dockerreg:5000/software/redis

# Define working directory.
WORKDIR /data

# Define default command.
CMD ["redis-server", "/etc/redis/redis.conf"]

# Expose ports.
EXPOSE 6379
